version: "3.9"

services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 9071 --reload
    ports:
      - "9071:9071"
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  worker:
    build: .
    command: celery -A app.workers.celery_app.celery_app worker --loglevel=info
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: zenstore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

volumes:
  postgres_data:
